### PR TITLE
Build ESM & CJS, expose via exports

### PR DESCRIPTION
**Pull request by jacogr**
My attempt on following up on a similar PR in `@noble/hashes` to build this via ESM and CJS.

Additions:

- Both ESM and CJS tsconfig.json files
- Small tweaks to the tsconfig files, e.g. esModuleInterop
- Builds ESM into lib/esm
- Now builds CJS into lib (reachable via the esport map)
- Uses export maps with import/default for the CJS/ESM mapping from lib/*
- Update rollup config to build from lib/es/index.js, includes removal of common-js rollup plugin
- Removed the root index.js file (these are now compiled into lib, I didn't check these in)

While there are now 3 files in the root (index.ts, crypto.ts & cryptoBrowser.ts) I didn't move these to a src folder.

Any comments welcome as well as insights in to where I may have missed the ball.

### CODE REVIEW

**Comment by paulmillr** [comment]
How does this work with `deno`?

**Comment by jacogr** [comment]
I am not a deno expert :) Having said that, looking at it while doing this, since the `mod.ts` still imports `index.ts` (no changes/movements there), I believed it was still correct and would work without any additions. 

I may be wrong  in that is may base a breakdown where it requires `@noble/secp256k1/crypto`, not sure how to solve that one. (Would be solvable no doubt, just not familiar with the deno environment)

**Comment by paulmillr** [comment]
I don't think it's solvable. We need to test it, since it seems to be the main lib for secp on deno

**Comment by jacogr** [comment]
Just testing with rollup, we do have `"browser": { "crypto": false }` in `package.json` -

1. Remove `crypto.ts` & `cryptoBrowser.ts`
2. Remove crypto import and add the following to `index.ts` -

```js
// Global symbol available in browsers only
declare const self: Record<string, any> | undefined;

import nodeCrypto from 'crypto';

export const crypto: { node?: any; web?: any } = {
  node: nodeCrypto,
  web: typeof self === 'object' && 'crypto' in self ? self.crypto : undefined,
};
```

The build output is as follows -

```js

**Comment by paulmillr** [comment]
There are other bundlers besides rollup like Browserify, webpack. They need to be considered also.

**Comment by paulmillr** [comment]
Build-release only builds single file for standalone in-browser inclusion btw, it is not used when node.js-required.

**Comment by jacogr** [comment]
Yes, I do understand the role of `build-release` very well :) The `"crypto": false` in `package.json` is not a rollup-specific flag, it is a field for bundlers. 

For webpack it ends up with an empty crypto require as well (CJS inputs) -

```js
var __webpack_modules__ = ({
// my comment - the module id for @noble/secp256k1
656: (function ...
...
const crypto_1 = __importDefault(__webpack_require__(159));
... /// more secp256k1 code
const crypto = {
    node: crypto_1.default,
    web: typeof self === 'object' && 'crypto' in self ? self.crypto : undefined,
};
... // more secp256k1 code
/***/ }), // send 656

/***/ 159:
/***/ (() => {

/* (ignored) */

/***/ })
... // more webpack code, here for the require impl
```

Steps to replicate -

1. new folder, cd folder
2. yarn init
3. yarn add webpack
4. dummy index.htm using index.js as sscript source
5. index.js file just importing util and executing randombytes on it (logging the output)
6. run webpack (I did add a small webpack.config.js file to set optimization false)

**Comment by paulmillr** [comment]
Could you resolve conflicts?

**Comment by paulmillr** [comment]
@jacogr the tests are failing

**Pull request merged**
