### PR TITLE
removed bigint exponentiation operator that crashes some builds

### PR DESCRIPTION
**Pull request by alex-nax**
fixes issue https://github.com/polkadot-js/common/issues/1321

### CODE REVIEW

**Comment by paulmillr** [comment]
This is rare bundler issue. I don't like to make the code shitty because of some exotic bundler builds. We have enough of shit code e.g. we're not using 1234n directly anymore.

**Comment by paulmillr** [comment]
e.g. `115792089237316195423570985008687907853269984665640564039457584007913129639936` needs to be verified by hand! 2**256 doesn't

**Comment by alex-nax** [comment]
> This is rare bundler issue. I don't like to make the code shitty because of some exotic bundler builds. We have enough of shit code e.g. we're not using 1234n directly anymore.

It fails on react-native environments

**Comment by paulmillr** [comment]
upgrade your react-native then.

**Comment by alex-nax** [comment]
the problem is with this code https://github.com/facebook/metro/blob/main/packages/metro-react-native-babel-preset/src/configs/main.js#L121

**Comment by lf94** [comment]
@paulmillr it'd be better performance-wise if this was used instead for the react-native variant...

**Comment by paulmillr** [comment]
@lf94 no it's not better. If you say it is better, provide some benchmarks.

**Pull request closed without merging**
