### PR TITLE
feat: sign with extraData and verify strict or not.

### PR DESCRIPTION
**Pull request by hank121314**
## Summary

1. add  `normalizeS` function to `Signature` to normalizes a signature to a "low S" form. 
2. add `strict` parameter to `verify`. If it is true, `signature.s` value greater than 1/2 prime order is rejected.
3. add `opts.extraData` option to `sign` as Added Entropy to the deterministic `k` generation.

## Thanks

Thanks for creating this awesome package!

This is my first contribution, please feel free to critique, and thanks for your code review 😄 .

### CODE REVIEW

**Comment by paulmillr** [comment]
Hi @hank121314 

Thanks for the contribution.

The questions:

1. Are you aware of any protocols that require / use `extraData` in deterministic k gen?
2. I assume it's safe for k reuse?

**Comment by hank121314** [comment]
> 1. Are you aware of any protocols that require / use extraData in deterministic k gen?

It seems that bitcoin can sign with low R-value, which will need to use extraData in deterministic k gen.
FYI: https://github.com/bitcoin/bitcoin/pull/13666

> 2. I assume it's safe for k reuse?

Yes, it will be safe if reusing k for the same message. Only when signing a different message with the same k will leak the private key.

**Comment by paulmillr** [comment]
We absolutely do not want users to be able to create dangerous signatures that will expose private keys.

Deterministic k is a huge improvement over `random k`, because it isn't really possible to create two different msgs with same `k`.

Now, my assumption was that `extraData` only adds entropy to the `k`, and not replaces `k` entirely. If that is not the case, I would not to add this feature.

Also, BTC has released Schnorr signatures which this library already supports. So it makes sense to focus on new, better signing, vs features for the old one.

**Comment by hank121314** [comment]
According to [RFC6979](https://datatracker.ietf.org/doc/html/rfc6979#section-3.6) extraData will be added to the input of HMAC, concatenated after `bits2octets(H(m))`.

```
K = HMAC_K(V || 0x00 || int2octets(x) || bits2octets(h1) || k')
```

It seems that `extraData` will only adds entropy to the k, and not replaces k entirely. 

Thank you very much for your detailed explanation.

**Comment by paulmillr** [comment]
We already have the check for `high s`, it's called `canonical: true`, doing `sign()` with `canonical: true` will produce `s` less than `curve.n >> 1n`.

**Comment by vae520283995** [comment]
@paulmillr 
bitcoincash updated to schnorr signature algorithm, see this link for details https://upgradespecs.bitcoincashnode.org/2019-05-15-schnorr/

```
Signers MUST NOT use straight RFC6979, since this is already used in many wallets doing ECDSA.
Suppose the same unsigned transaction were accidentally passed to both ECDSA and Schnorr wallets holding same key, which in turn were to generate the same RFC6979 k. This would be obvious (same r values) and in turn allow recovery of the private key from the distinct Schnorr s and ECDSA s' values: x = (±ss'-z)/(r±s'e) mod n.
We suggest using the RFC6979 sec 3.6 'additional data' mechanism, by appending the 16-byte ASCII string "Schnorr+SHA256␣␣" (here ␣ represents 0x20 -- ASCII space). The popular library libsecp256k1 supports passing a parameter algo16 to nonce_function_rfc6979 for this purpose.
```

**Comment by paulmillr** [comment]
1. I have added `hasHighS()` method to `Signature`, but I don't want to add `negateS()` for now. We're doing S negation in `QRSToSig` already: exposing the method seems unnecessary. Exposing `hasHighS()` has some benefits e.g. see the same check here https://github.com/paulmillr/micro-eth-signer/blob/e86d02f2fa0893649ede0d73acbae83dbcec55bb/index.ts#L492
2. Note that https://github.com/bitcoin/bitcoin/pull/13666 implements `high R` checks, not `high S`. High s checks were done for a long time in BTC, also in ETH.
3. I'm not sure we should add `strict` option to `verify()`. Why `strict` and not `canonical` that matches `sign()`? Also, does `libsecp256k1` itself implement strict verification? Is there an option/flag, or is it always strict? Mainly thinking about what others do.
4. As for additional data `k'` from RFC6979 sec 3.6, it seems useful, but my main concern is still the same: will reusing it leak the private key? If yes, I won't add it, because it introduces a way to use the `noble-secp` in an insecure, covert way. I have asked other folks for the `k'` question, let's see what they'll say. Also, note that 3.6 is completely optional, and there are no official test vectors for it.
5. @vae520283995 as for bch, I find it strange 

>Signers MUST NOT use straight RFC6979, since this is already used in many wallets doing ECDSA.
> Suppose the same unsigned transaction were accidentally passed to both ECDSA and Schnorr wallets holding same key

This seems improbable to me. Why would you construct the same TX with Schnorr + ECDSA at the same time? Most wallets have checks whether the address is using `bech` addresses, or not. E.g. it's either bech or old-style. Same with schnorr vs old style.

> Hardware wallets SHOULD use deterministic nonce due to the lack of CSRNG

Also, they're mentioning that hardware wallets must not use `k'` because it makes them less secure.

**Comment by paulmillr** [comment]
See https://crypto.stackexchange.com/questions/97911/reusing-additional-data-k-nonce-from-rfc6979-ecdsa for point no. 4

**Comment by paulmillr** [comment]
So it seems like we should be safe. One last question is param name. `extraEntropy` vs `extraData` vs `additionalData`. Does anyone know what other libraries use?

**Comment by vae520283995** [comment]
> > Signers MUST NOT use straight RFC6979, since this is already used in many wallets doing ECDSA.
> > Suppose the same unsigned transaction were accidentally passed to both ECDSA and Schnorr wallets holding same key
> 
> This seems improbable to me. Why would you construct the same TX with Schnorr + ECDSA at the same time? Most wallets have checks whether the address is using `bech` addresses, or not. E.g. it's either bech or old-style. Same with schnorr vs old style.
> 

The cash address in bch is different from the segwit address in btc, in bch the cash address and the legacy address in are just different in format but the script is the same. The segwit address in btc uses a new script. When bch supports schnorr signatures, ecdsa and schnorr signatures exist at the same time. If we use both ecdsa and schnorr at the same time, if both k Using the original rfc6979, then using the same k will be dangerous, so bch recommends adding additional data to ensure that the k value is different from the original ecdsa

**Comment by vae520283995** [comment]
I just checked a few libraries, and I found that I misunderstood. The schnorr signature in bch does not use the extra data in rfc6979, but algo16. You can check the implementation of bch and btc
https://gitlab.com/bitcoin-cash-node/bitcoin-cash-node/-/blob/master/src/secp256k1/src/modules/schnorr/schnorr_impl.h#L226
```
 /* Seed used to make sure we generate different values of k for schnorr */
    const unsigned char secp256k1_schnorr_algo16[17] = "Schnorr+SHA256  ";

```
https://github.com/bitcoin-core/secp256k1/blob/0559fc6e41b65af6e52c32eb9b1286494412a162/src/secp256k1.c#L421
```
/* We feed a byte array to the PRNG as input, consisting of:
    * - the private key (32 bytes) and message (32 bytes), see RFC 6979 3.2d.
    * - optionally 32 extra bytes of data, see RFC 6979 3.6 Additional Data.
    * - optionally 16 extra bytes with the algorithm name.
    * Because the arguments have distinct fixed lengths it is not possible for
    *  different argument mixtures to emulate each other and result in the same
    *  nonces.
    */
```

**Comment by paulmillr** [comment]
I think using 16 bytes of algo is basically the same as using the same bytes in `k'` / `extraEntropy`?

**Comment by vae520283995** [comment]
> I think using 16 bytes of algo is basically the same as using the same bytes in `k'` / `extraEntropy`?

yes

**Comment by hank121314** [comment]
> I'm not sure we should add strict option to verify(). Why strict and not canonical that matches sign()? Also, does libsecp256k1 itself implement strict verification? Is there an option/flag, or is it always strict? Mainly thinking about what others do.

`libsecp256k1` does not implement optional strict verification it is always strict. 
But in this library `verify` can verify both canonical and non-canonical signatures, it seems strict option might be unnecessary.

> I have added hasHighS() method to Signature, but I don't want to add negateS() for now.

I would like to expose the `negateS` cause if users create a signature with `fromCompact` or `fromDER`, which might create a non-canonical signature.
Exposing `negateS` can help users to normalize a non-canonical signature to a canonical signature.

Thanks!

**Comment by paulmillr** [comment]
>Exposing negateS can help users to normalize a non-canonical signature to a canonical signature.

Can you provide an example of a real app flow that does this?

If you're creating a new signature, simply pass `canonical` flag to create a proper one.

If you're parsing an old signature, there is no point in making it canonical, because it will make it different.

**Comment by paulmillr** [comment]
@hank121314 Can you provide any proofs that `libsecp256k1` `verify` always does low-s checks? From my research, that seems to be incorrect.

**Comment by hank121314** [comment]
> If you're parsing an old signature, there is no point in making it canonical, because it will make it different.

AFAIK, although it is different, it is still a valid key for the same message and signing key.
And there are also some benefits for canonical signature, which are mentioned in https://github.com/bitcoin-core/secp256k1/blob/a1102b12196ea27f44d6201de4d25926a2ae9640/include/secp256k1.h#L530-L534 .

Thanks for pointing out if I have misunderstood anything!

**Comment by hank121314** [comment]
> @hank121314 Can you provide any proofs that `libsecp256k1` `verify` always does low-s checks? From my research, that seems to be incorrect.

In my research, I found these clues.

1. https://github.com/bitcoin-core/secp256k1/blob/a1102b12196ea27f44d6201de4d25926a2ae9640/include/secp256k1.h#L546-L549
2. low-S check is declared in this line https://github.com/bitcoin-core/secp256k1/blob/a1102b12196ea27f44d6201de4d25926a2ae9640/src/secp256k1.c#L411 and implemented in https://github.com/bitcoin-core/secp256k1/blob/a1102b12196ea27f44d6201de4d25926a2ae9640/src/scalar_4x64_impl.h#L158-L168 for 64bits.

**Comment by paulmillr** [comment]
I have implemented canonical check in verify. I will likely make it default in 1.4.0. Thanks for your help!

**Comment by paulmillr** [comment]
@hank121314 one last question is: why did you do this check? It should be `toBeFalsy()`, isn't it?


```
          if (e.strict === true) {
             expect(secp.verify(signature, m, Q, false)).toBeTruthy();
           }
```

**Comment by hank121314** [comment]
> @hank121314 one last question is: why did you do this check? It should be `toBeFalsy()`, isn't it?

This will only check this fixture(from https://github.com/bitcoinjs/tiny-secp256k1/blob/45b0cc2e9195cecdba209fb237fa0095d88e7a24/tests/fixtures/ecdsa.json#L10305-L10311):

```json
{
        "description": "Fails verification if strict set to truthy value with high s value",
        "strict": true,
        "Q": "034cd032cdc72820498aeb0fdd25712aa4f6d263997cf7df140b8c42d44626b08c",
        "m": "df8e1382d17bdac18f3c854815071226385803e85f06114129ebbcfcef991278",
        "signature": "ec8cd8d7dcda4ff770c2858bdd93dd64806e218b11bb1971a4a09b065760b040c1095cf554dab161b2b2c46386fab2c81e57035be714b760ef507981f8f70073"
}
```

In my implementation, only if `strict` is false will do `normalizeS`.
And `verify` will reject the signature that has a high s value.
This seems to be opposite to `canonical` means.
And like the description says. 

```javascript
// If strict is true, it will never do normalizeS and it will has a high s value so the check will never pass.
expect(secp.verify(signature, m, Q, e.strict)).toBeFalsy();
if (e.strict === true) {
  // If strict is false, it will do normalizeS and it will has a low s value. It should pass the check.
  expect(secp.verify(signature, m, Q, false)).toBeTruthy();
}
```

I would like your implementation now. 
Using `option.canonical` to let users choose which form should be used in verify.
This will be more general.

Thank you for the great discussion 🚀 ! Learn a lot from it 😃 !

**Comment by paulmillr** [comment]
@hank121314 We won't normalize signatures because libsecp doesn't do it. However, if you'd like, you could use `strict: false`, or normalize it by yourself. I have removed normalizeS from verify.

**Pull request closed without merging**
